[[pp_lib]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "ee1b578df8292629554c3af06740b7b7ce4a3a70"
lazy = true
    [[pp_lib.download]]
    sha256 = "2d9fecaded001f4297dc4351b2bab7b4da41a9b4c57d2c3ec284db840affb441"
    #url = "file:///home/john/work/julia/pp_lib.tar.gz"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

[[pp_lib]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "ee1b578df8292629554c3af06740b7b7ce4a3a70"
lazy = true
    [[pp_lib.download]]
    sha256 = "2d9fecaded001f4297dc4351b2bab7b4da41a9b4c57d2c3ec284db840affb441"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

