[[pp_lib]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "15515d13c7aae81a3c08c64313aec7ee6020b694"
lazy = true
    [[pp_lib.download]]
    sha256 = "092c6bd14f5247e31d1a67540894765531a413161156c861b6638de170599be3"
    #url = "file:///home/john/work/julia/pp_lib.tar.gz"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

[[pp_lib]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "15515d13c7aae81a3c08c64313aec7ee6020b694"
lazy = true
    [[pp_lib.download]]
    sha256 = "092c6bd14f5247e31d1a67540894765531a413161156c861b6638de170599be3"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

